# Generated by Django 5.2.14 on 2026-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('super_user', 'Super User'), ('site_admin', 'Site Admin'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
