# Generated by Django 5.2.14 on 2026-06-12 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name (e.g., 'Users', 'Briefcase')", max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color or CSS class', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
            ],
            options={
                'verbose_name_plural': 'Template Categories',
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('estimated_tasks', models.IntegerField(default=0, help_text='Auto-updated or manual estimate')),
                ('estimated_duration', models.CharField(blank=True, help_text="e.g., '2 Weeks'", max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('columns', models.JSONField(blank=True, default=list, help_text='Custom columns/sections for this template')),
                ('milestones', models.JSONField(blank=True, default=list, help_text='List of milestones to create when cloning')),
                ('default_members', models.JSONField(blank=True, default=list, help_text='Roles or specific users to add to the project')),
                ('workflow_settings', models.JSONField(blank=True, default=dict, help_text='Workflow automation triggers and actions')),
                ('is_public', models.BooleanField(default=True, help_text='Available in the marketplace')),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='templatesapp.templatecategory')),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(default='P3', max_length=20)),
                ('default_status', models.CharField(default='pending', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('due_days_after_project_creation', models.IntegerField(default=0, help_text='Number of days after project creation this task should be due.', validators=[django.core.validators.MinValueValidator(0)])),
                ('assignee_role', models.CharField(blank=True, help_text='Role to map to real user during import', max_length=50)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_template_tasks', to='templatesapp.templatetask')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='templatesapp.templatetask')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='templatesapp.template')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
