# Generated by Django 5.2.14 on 2026-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_site_organization_site_location'),
        ('templatesapp', '0002_template_site_templatecategory_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('slug', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='templatecategory',
            unique_together={('slug', 'organization'), ('title', 'organization')},
        ),
    ]
