# Generated by Django 5.2.14 on 2026-06-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_assigned_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='site',
            new_name='site_location',
        ),
    ]
