# Generated by Django 5.2.14 on 2026-07-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_site_organization_site_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='advanced_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
