# Generated by Django 5.2.14 on 2026-06-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='WorkHub', max_length=150)),
                ('primaryColor', models.CharField(default='#2563EB', max_length=20)),
                ('accentColor', models.CharField(default='#7C3AED', max_length=20)),
                ('logo', models.TextField(blank=True, default='')),
                ('font', models.CharField(default='inter', max_length=50)),
                ('customDomain', models.CharField(blank=True, default='', max_length=100)),
                ('companyWebsite', models.CharField(blank=True, default='https://www.yourcompany.com', max_length=200)),
                ('darkModeDefault', models.BooleanField(default=False)),
                ('showWelcomeBanner', models.BooleanField(default=True)),
                ('sidebarStyle', models.CharField(default='full', max_length=50)),
            ],
        ),
    ]
