# Generated by Django 5.2.14 on 2026-06-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsetting',
            name='favicon',
            field=models.TextField(blank=True, default=''),
        ),
    ]
