# Generated by Django 5.2.14 on 2026-07-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_article_file_alter_article_content_and_more'),
        ('organization', '0004_rename_site_organization_site_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='articlecategory',
            unique_together={('slug', 'organization')},
        ),
    ]
