# Generated by Django 5.2.14 on 2026-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_channel_organization_channel_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
