# Generated by Django 5.2.14 on 2026-06-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='bg-primary', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_timeline_cards', to='boards.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='card',
            name='start_day',
            field=models.IntegerField(default=0),
        ),
    ]
