# Generated by Django 5.2.14 on 2026-06-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_activitylog_site_project_site_projectmilestone_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_type',
            field=models.CharField(blank=True, default='blank', max_length=100),
        ),
    ]
