# Generated by Django 5.2.14 on 2026-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_task_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_effort',
            field=models.IntegerField(default=0),
        ),
    ]
