# Generated by Django 5.2.14 on 2026-07-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_task_actual_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_interval_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
