# Generated by Django 5.2.14 on 2026-07-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_task_deadline_alert_sent_task_is_queued_and_more'),
        ('organization', '0005_organization_advanced_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='taskchat',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='taskchat',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
    ]
