# Generated by Django 5.2.14 on 2026-07-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_alter_activitylog_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='effort_unit',
            field=models.CharField(default='hours', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_effort',
            field=models.IntegerField(default=3),
        ),
    ]
