# Generated by Django 5.2.14 on 2026-08-03 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_task_effort_unit_task_estimated_effort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='api_multi_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
