# Generated by Django 5.2.14 on 2026-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
