# Generated by Django 5.2.14 on 2026-06-12 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_attendees', models.TextField(blank=True, help_text='Comma-separated emails', null=True)),
                ('meeting_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(default='30 mins', max_length=50)),
                ('meeting_type', models.CharField(choices=[('internal', 'Internal Review'), ('client', 'Client Sync'), ('standup', 'Daily Standup'), ('workshop', 'Workshop/Training')], default='internal', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, db_table='api_meeting_attendees', related_name='api_meetings_attending', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_organized_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_meeting',
                'ordering': ['meeting_time'],
            },
        ),
    ]
