# Generated by Django 5.2.14 on 2026-07-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_requests', '0003_leaderboardentry_attendancerecord'),
        ('organization', '0005_organization_advanced_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='hrrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='hrrequest',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='hrrequestlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='hrrequestlog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
    ]
