# Generated by Django 5.2.14 on 2026-06-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=3)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='active', max_length=20)),
                ('joined_date', models.CharField(max_length=20)),
                ('manager', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
