# Generated by Django 5.2.14 on 2026-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0002_mompoint_end_date_mompoint_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mom',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mom',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mom',
            name='meeting_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='mom',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('monthly review', 'Monthly Review'), ('weekly sync', 'Weekly Sync'), ('quaterly business review', 'Quaterly Business Review'), ('escalation', 'Escalation')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mom',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mom',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mom',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mom',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags'),
        ),
    ]
