# Generated by Django 5.2.14 on 2026-06-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0004_momattendee'),
        ('organization', '0003_remove_organization_assigned_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mompoint',
            old_name='end_date',
            new_name='actual_date',
        ),
        migrations.RenameField(
            model_name='mompoint',
            old_name='start_date',
            new_name='planned_date',
        ),
        migrations.AddField(
            model_name='mompoint',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mompoint',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='mompoint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='MOMAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='mom.mom')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site_records', to='organization.site')),
            ],
            options={
                'db_table': 'api_mom_agenda',
                'ordering': ['created_at'],
            },
        ),
    ]
