# Generated by Django 5.2.14 on 2026-07-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0005_rename_end_date_mompoint_actual_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mom',
            name='meeting_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in progress', 'In Progress'), ('Completed', 'Completed'), ('cancelled', 'Cancelled'), ('Draft', 'Draft')], default='scheduled', max_length=50),
        ),
    ]
