# Generated by Django 5.2.14 on 2026-06-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_userprofile_site'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='teamactivity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site_records', to='organization.site'),
        ),
    ]
