# Generated by Django 5.2.14 on 2026-06-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0003_courseaccessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('title_text', models.CharField(default='Certificate of Completion', max_length=255)),
                ('body_text', models.TextField(default='This certifies that {{employee_name}} has successfully completed the course.')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
