# Generated by Django 5.2.14 on 2026-06-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0004_certificatetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVideoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_pause', models.BooleanField(default=True)),
                ('idle_timeout_seconds', models.IntegerField(default=120)),
                ('disable_fast_forward', models.BooleanField(default=True)),
                ('watch_percentage_required', models.IntegerField(default=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('max_progress_seconds', models.FloatField(default=0.0)),
                ('last_position_seconds', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning_center.coursepoint')),
            ],
            options={
                'unique_together': {('employee_name', 'course_point')},
            },
        ),
    ]
