# Generated by Django 5.2.14 on 2026-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0005_globalvideosettings_videoprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
