# Generated by Django 5.2.14 on 2026-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0007_globalvideosettings_assessment_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='validity_days',
            field=models.IntegerField(default=365, help_text='Number of days the certificate is valid. 0 means infinite.'),
        ),
    ]
