# Generated by Django 5.2.14 on 2026-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0008_certificatetemplate_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvideosettings',
            name='max_assessment_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
