# Generated by Django 5.2.14 on 2026-06-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0009_globalvideosettings_max_assessment_attempts'),
        ('organization', '0004_rename_site_organization_site_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site_records', to='organization.site'),
        ),
    ]
