# Generated by Django 5.2.14 on 2026-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0010_course_organization_course_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvideosettings',
            name='max_assessment_warnings',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='globalvideosettings',
            name='require_video_completion',
            field=models.BooleanField(default=True),
        ),
    ]
