# Generated by Django 5.2.14 on 2026-07-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0011_globalvideosettings_max_assessment_warnings_and_more'),
        ('organization', '0005_organization_advanced_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='courseaccessrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='courseaccessrequest',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='coursefaq',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='coursefaq',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='coursepoint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='coursepoint',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='coursepointquestion',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='coursepointquestion',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='globalvideosettings',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='globalvideosettings',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
    ]
