from django.db.models.signals import post_save
from django.dispatch import receiver
from Project.models import Task
from .models import Workflow
from .utils import execute_workflow_engine

@receiver(post_save, sender=Task)
def task_created_trigger(sender, instance, created, **kwargs):
    """
    Triggers workflows that have 'Task Created' as their starting node.
    """
    if created:
        # Avoid circular dependencies or infinite loops
        # by checking if this task was created by the workflow engine itself.
        if "Workflow Auto-Task" in instance.title or "Automatically generated by workflow" in instance.description:
            return

        # Find all active workflows for the same organization
        workflows = Workflow.objects.filter(active=True)
        if instance.organization:
            workflows = workflows.filter(organization=instance.organization)

        for workflow in workflows:
            nodes_list = workflow.nodes.get('nodes', []) if isinstance(workflow.nodes, dict) else workflow.nodes
            if not nodes_list:
                continue

            # Check if this workflow's start nodes contain 'Task Created'
            edges = workflow.nodes.get('edges', []) if isinstance(workflow.nodes, dict) else []
            target_nodes = set(edge.get('target') for edge in edges)
            start_nodes = [node for node in nodes_list if node['id'] not in target_nodes]
            
            trigger_match = False
            for node in start_nodes:
                if node.get('data', {}).get('label') == 'Task Created':
                    trigger_match = True
                    break
            
            if trigger_match:
                # Execute the workflow engine in the background thread
                import threading
                try:
                    threading.Thread(target=execute_workflow_engine, args=(workflow,), kwargs={'user_context': instance.created_by, 'context_task': instance}).start()
                except Exception as e:
                    print(f"Error executing event-driven workflow {workflow.name}: {e}")
