import datetime
import json
from django.apps import apps
from django.contrib.auth import get_user_model
from django.conf import settings
from .models import WorkflowLog

def execute_workflow_engine(workflow, user_context=None, context_task=None, raise_errors=False):
    """
    Executes a Workflow dynamically in real-time.
    :param workflow: The Workflow model instance.
    :param user_context: The User model instance triggering the workflow (used as fallback assignee/creator).
    :param context_task: A Task model instance if this workflow was triggered by a specific task.
    """
    nodes_list = workflow.nodes.get('nodes', []) if isinstance(workflow.nodes, dict) else workflow.nodes
    edges = workflow.nodes.get('edges', []) if isinstance(workflow.nodes, dict) else []
    nodes_count = len(nodes_list)
    
    if not nodes_list:
        return
        
    User = get_user_model()
    try:
        Notification = apps.get_model('workspace', 'Notification')
    except LookupError:
        Notification = None
        
    adj = {}
    nodes_dict = {node['id']: node for node in nodes_list}
    
    for edge in edges:
        src = edge.get('source')
        tgt = edge.get('target')
        handle = edge.get('sourceHandle')
        if src not in adj:
            adj[src] = []
        adj[src].append((tgt, handle))
            
    target_nodes = set(edge.get('target') for edge in edges)
    start_nodes = [node['id'] for node in nodes_list if node['id'] not in target_nodes]
    if not start_nodes and nodes_list:
        start_nodes = [nodes_list[0]['id']]
        
    execution_queue = list(start_nodes)
    visited = set()
    node_traces = {}
    
    while execution_queue:
        curr = execution_queue.pop(0)
        if curr in visited: continue
        visited.add(curr)
        
        node = nodes_dict.get(curr)
        if not node: continue
        
        label = node.get('data', {}).get('label', 'Node')
        config = node.get('data', {}).get('config', {})
        
        log_msg = f"Successfully executed '{label}'."
        branch_taken = None
        
        if label in ["Task Created", "Request Submitted"]:
            log_msg = f"Trigger '{label}' processed."

        elif label == "Create Task":
            from Project.models import Task
            from django.utils import timezone
            task_title = config.get('taskTitle', f"Workflow Auto-Task: {workflow.name}")
            task_desc = config.get('taskDesc', f"Automatically generated by workflow '{workflow.name}'.")
            assignee_id = config.get('assignee')
            
            created_by_user = user_context if user_context else User.objects.filter(is_superuser=True).first()
            
            new_task = Task.objects.create(
                title=task_title,
                description=task_desc,
                created_by=created_by_user,
                status="pending",
                due_date=timezone.now().date(),
                organization=workflow.organization
            )
            
            if assignee_id:
                try:
                    assignee = User.objects.get(id=assignee_id)
                    new_task.assigned_to = assignee
                    new_task.save()
                    log_msg = f"Action '{label}' executed. Created real task '{new_task.title}' assigned to {assignee.get_full_name() or assignee.username}."
                except User.DoesNotExist:
                    log_msg = f"Action '{label}' executed. Created real task '{new_task.title}'. Assignee ID {assignee_id} not found."
            else:
                log_msg = f"Action '{label}' executed. Created real task '{new_task.title}' without assignee."
            
            if not context_task:
                context_task = new_task
                        
        elif label == "Assign User":
            assign_type = config.get('assignType', 'self')
            
            assignee_id = config.get('assignee')
            if assign_type == "self" and user_context:
                assignee_id = user_context.id
                
            if assignee_id:
                try:
                    user = User.objects.get(id=assignee_id)
                    if context_task:
                        context_task.assigned_to = user
                        context_task.save()
                    log_msg = f"Successfully assigned workflow task to {user.get_full_name() or user.username}."
                    if Notification:
                        Notification.objects.create(
                            type="workflow_assignment",
                            title="Workflow Assignment",
                            message=f"You have been assigned to a step in workflow: '{workflow.name}'",
                            link="/workflow-automation",
                            organization=workflow.organization,
                            user=user
                        )
                    if user.email:
                        from django.core.mail import send_mail
                        try:
                            send_mail(
                                subject=f"Workflow Assignment: {workflow.name}",
                                message=f"Hello {user.get_full_name() or user.username},\n\nYou have been assigned a task from workflow '{workflow.name}'.\n\n- System Bot",
                                from_email=settings.DEFAULT_FROM_EMAIL,
                                recipient_list=[user.email],
                                fail_silently=False,
                            )
                            log_msg += " Real email dispatched."
                        except Exception as e:
                            log_msg += f" Email failed: {str(e)}"
                            if raise_errors:
                                raise Exception(f"Email failed: {str(e)}")
                except User.DoesNotExist:
                    log_msg = f"Assignee ID '{assignee_id}' not found. Cannot assign user."
                    
        elif label == "Assign Manager":
            manager_id = config.get('managerId')
            if manager_id:
                try:
                    manager = User.objects.get(id=manager_id)
                    if context_task:
                        context_task.assigned_to = manager
                        context_task.save()
                    log_msg = f"Successfully assigned workflow task to manager {manager.get_full_name() or manager.username}."
                    if Notification:
                        Notification.objects.create(
                            type="workflow_assignment",
                            title="Manager Assignment",
                            message=f"You have been assigned as a manager for a step in workflow: '{workflow.name}'",
                            link="/workflow-automation",
                            organization=workflow.organization,
                            user=manager
                        )
                    if manager.email:
                        from django.core.mail import send_mail
                        try:
                            send_mail(
                                subject=f"Manager Assignment: {workflow.name}",
                                message=f"Hello {manager.get_full_name() or manager.username},\n\nYou have been assigned a task as a Manager from workflow '{workflow.name}'.\n\n- System Bot",
                                from_email=settings.DEFAULT_FROM_EMAIL,
                                recipient_list=[manager.email],
                                fail_silently=False,
                            )
                            log_msg += " Real email dispatched."
                        except Exception as e:
                            log_msg += f" Email failed: {str(e)}"
                            if raise_errors:
                                raise Exception(f"Email failed: {str(e)}")
                except User.DoesNotExist:
                    log_msg = f"Manager ID '{manager_id}' not found. Cannot assign manager."
                    
        elif label == "Role Condition":
            required_role = config.get('role', 'Manager').lower()
            user_role = "employee"
            if user_context and hasattr(user_context, 'auth_profile'):
                profile = user_context.auth_profile
                if getattr(profile, 'role_relationship', None):
                    user_role = profile.role_relationship.name.lower()
                else:
                    user_role = profile.role.lower()

            if user_role == required_role:
                branch_taken = "true"
                log_msg = f"Condition evaluated to True: User role '{user_role}' matches required '{required_role}'."
            else:
                branch_taken = "false"
                log_msg = f"Condition evaluated to False: User role '{user_role}' does not match required '{required_role}'."

        elif label == "Update Status":
            new_status = config.get('status', 'Pending').lower()
            if context_task:
                context_task.status = new_status
                context_task.save()
                log_msg = f"Updated context task status to '{new_status}'."
            else:
                log_msg = f"No active task context found to update status to '{new_status}'."
                        
        elif label in ["Approval Step", "Approval Needed"]:
            approver_id = config.get('approvers')
            if approver_id:
                try:
                    user = User.objects.get(id=approver_id)
                    mode = config.get('mode', 'parallel')
                    log_msg = f"Requested {mode} approval from {user.get_full_name() or user.username}."
                    if Notification:
                        Notification.objects.create(
                            type="workflow_approval",
                            title="Approval Required",
                            message=f"Your approval is required to proceed with workflow: '{workflow.name}'",
                            link="/workflow-automation",
                            organization=workflow.organization,
                            user=user
                        )
                    if user.email:
                        from django.core.mail import send_mail
                        try:
                            send_mail(
                                subject=f"Approval Required: {workflow.name}",
                                message=f"Hello {user.get_full_name() or user.username},\n\nYour approval is required to proceed with workflow '{workflow.name}'.\n\n- System Bot",
                                from_email=settings.DEFAULT_FROM_EMAIL,
                                recipient_list=[user.email],
                                fail_silently=True,
                            )
                            log_msg += " Real email dispatched."
                        except Exception:
                            pass
                except User.DoesNotExist:
                    log_msg = f"Approver ID '{approver_id}' not found. Cannot request approval."
                    
        elif label == "Send Email":
            email_address = config.get('email')
                
            subject = config.get('subject', f"Workflow Notification: {workflow.name}")
            body = config.get('body', f"Hello,\n\nThis is an automated email from the workflow '{workflow.name}'.\n\n- System Bot")
            if email_address:
                from django.core.mail import send_mail
                try:
                    send_mail(
                        subject=subject,
                        message=body,
                        from_email=settings.DEFAULT_FROM_EMAIL,
                        recipient_list=[email_address],
                        fail_silently=False,
                    )
                    log_msg = f"Successfully dispatched real email to {email_address} with subject '{subject}'."
                except Exception as e:
                    log_msg = f"Failed to send email to {email_address}. Error: {str(e)}"
                    if raise_errors:
                        raise Exception(f"Failed to send email to {email_address}. SMTP Error: {str(e)}")
            else:
                log_msg = f"No recipient email configured for Send Email node."
                
        elif label == "Send Notification":
            title = config.get('title', f"Workflow Alert: {workflow.name}")
            message = config.get('message', 'A workflow automation step was triggered.')
            target_user_id = config.get('userId')
            
            target_user = None
            if target_user_id:
                try:
                    target_user = User.objects.get(id=target_user_id)
                except User.DoesNotExist:
                    pass
            
            if Notification:
                Notification.objects.create(
                    type="workflow_alert",
                    title=title,
                    message=message,
                    link="/workflow-automation",
                    organization=workflow.organization,
                    user=target_user
                )
                if target_user:
                    log_msg = f"Targeted notification dispatched to {target_user.get_full_name() or target_user.username}: '{title}'."
                else:
                    log_msg = f"Broadcast notification dispatched successfully: '{title}'."

        node_traces[curr] = {
            "status": "Success",
            "timestamp": datetime.datetime.now().isoformat(),
            "log": log_msg
        }
        
        for target_id, handle in adj.get(curr, []):
            if branch_taken is None or handle == branch_taken or handle is None:
                execution_queue.append(target_id)

    log_details_dict = {
        "summary": f"Workflow executed sequentially across {nodes_count} connected nodes.\nAll actions completed and tracked.",
        "node_traces": node_traces
    }

    WorkflowLog.objects.create(
        workflow=workflow,
        status="Success",
        details=json.dumps(log_details_dict, indent=2),
        organization=workflow.organization
    )
    
    workflow.runs += 1
    workflow.last_run = datetime.datetime.now().isoformat()
    workflow.save(update_fields=['runs', 'last_run'])
