from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from .models import Workflow, WorkflowLog, WorkflowDefinition, WorkflowVersion, WorkflowExecution, ApprovalTask
from .serializers import WorkflowSerializer, WorkflowDefinitionSerializer, WorkflowVersionSerializer, WorkflowExecutionSerializer, ApprovalTaskSerializer
import datetime
from django.apps import apps
from django.contrib.auth import get_user_model

class WorkflowViewSet(viewsets.ModelViewSet):
    queryset = Workflow.objects.all().order_by('-created_at')
    serializer_class = WorkflowSerializer

    @action(detail=True, methods=['post'])
    def execute(self, request, pk=None):
        workflow = self.get_object()
        import json
        
        node_traces = {}
        nodes_list = workflow.nodes.get('nodes', []) if isinstance(workflow.nodes, dict) else workflow.nodes
        edges = workflow.nodes.get('edges', []) if isinstance(workflow.nodes, dict) else []
        nodes_count = len(nodes_list)
        
        current_time = datetime.datetime.now()
        
        # Load external models dynamically
        User = get_user_model()
        try:
            Notification = apps.get_model('workspace', 'Notification')
        except LookupError:
            Notification = None
            
        # Graph Execution Engine - Real-Time Dynamic Traversal
        adj = {}
        nodes_dict = {node['id']: node for node in nodes_list}
        
        for edge in edges:
            src = edge.get('source')
            tgt = edge.get('target')
            handle = edge.get('sourceHandle')
            if src not in adj:
                adj[src] = []
            adj[src].append((tgt, handle))
                
        target_nodes = set(edge.get('target') for edge in edges)
        start_nodes = [node['id'] for node in nodes_list if node['id'] not in target_nodes]
        if not start_nodes and nodes_list:
            start_nodes = [nodes_list[0]['id']]
            
        execution_queue = list(start_nodes)
        visited = set()
        
        context_task = None  # To hold dynamically created Task object
        
        while execution_queue:
            curr = execution_queue.pop(0)
            if curr in visited: continue
            visited.add(curr)
            
            node = nodes_dict.get(curr)
            if not node: continue
            
            label = node.get('data', {}).get('label', 'Node')
            config = node.get('data', {}).get('config', {})
            
            log_msg = f"Successfully executed '{label}'."
            branch_taken = None  # None = all branches, "true" = true branch, "false" = false branch
            
            if label in ["Task Created", "Request Submitted"]:
                # Create a task in Project app dynamically
                from Project.models import Task
                from django.utils import timezone
                context_task = Task.objects.create(
                    title=f"Workflow Auto-Task: {workflow.name}",
                    description=f"Automatically generated by workflow '{workflow.name}'.",
                    created_by=request.user,
                    status="pending",
                    due_date=timezone.now().date()
                )
                log_msg = f"Trigger '{label}' fired. Created real task '{context_task.title}'."
                            
            elif label == "Assign User":
                assign_type = config.get('assignType', 'self')
                assignee_id = config.get('assignee') if assign_type == "other" else request.user.id
                if assignee_id:
                    try:
                        user = User.objects.get(id=assignee_id)
                        if context_task:
                            context_task.assigned_to = user
                            context_task.save()
                        log_msg = f"Successfully assigned workflow task to {user.get_full_name() or user.username}."
                        if Notification:
                            Notification.objects.create(
                                type="workflow_assignment",
                                title="Workflow Assignment",
                                message=f"You have been assigned to a step in workflow: '{workflow.name}'",
                                link="/workflow-automation"
                            )
                        if user.email:
                            from django.core.mail import send_mail
                            try:
                                send_mail(
                                    subject=f"Workflow Assignment: {workflow.name}",
                                    message=f"Hello {user.get_full_name() or user.username},\n\nYou have been assigned a task from workflow '{workflow.name}'.\n\n- System Bot",
                                    from_email='system@company.local',
                                    recipient_list=[user.email],
                                    fail_silently=False,
                                )
                                log_msg += " Real email dispatched."
                            except Exception as e:
                                log_msg += f" Email failed: {str(e)}"
                    except User.DoesNotExist:
                        log_msg = f"Assignee ID '{assignee_id}' not found. Cannot assign user."
                        
            elif label == "Assign Manager":
                manager_id = config.get('managerId')
                if manager_id:
                    try:
                        manager = User.objects.get(id=manager_id)
                        if context_task:
                            context_task.assigned_to = manager
                            context_task.save()
                        log_msg = f"Successfully assigned workflow task to manager {manager.get_full_name() or manager.username}."
                        if Notification:
                            Notification.objects.create(
                                type="workflow_assignment",
                                title="Manager Assignment",
                                message=f"You have been assigned as a manager for a step in workflow: '{workflow.name}'",
                                link="/workflow-automation"
                            )
                        if manager.email:
                            from django.core.mail import send_mail
                            try:
                                send_mail(
                                    subject=f"Manager Assignment: {workflow.name}",
                                    message=f"Hello {manager.get_full_name() or manager.username},\n\nYou have been assigned a task as a Manager from workflow '{workflow.name}'.\n\n- System Bot",
                                    from_email='system@company.local',
                                    recipient_list=[manager.email],
                                    fail_silently=False,
                                )
                                log_msg += " Real email dispatched."
                            except Exception as e:
                                log_msg += f" Email failed: {str(e)}"
                    except User.DoesNotExist:
                        log_msg = f"Manager ID '{manager_id}' not found. Cannot assign manager."
                        
            elif label == "Role Condition":
                required_role = config.get('role', 'Manager').lower()
                user_role = "employee"
                if hasattr(request.user, 'auth_profile'):
                    profile = request.user.auth_profile
                    if getattr(profile, 'role_relationship', None):
                        user_role = profile.role_relationship.name.lower()
                    else:
                        user_role = profile.role.lower()

                if user_role == required_role:
                    branch_taken = "true"
                    log_msg = f"Condition evaluated to True: User role '{user_role}' matches required '{required_role}'."
                else:
                    branch_taken = "false"
                    log_msg = f"Condition evaluated to False: User role '{user_role}' does not match required '{required_role}'."

            elif label == "Update Status":
                new_status = config.get('status', 'Pending').lower()
                if context_task:
                    context_task.status = new_status
                    context_task.save()
                    log_msg = f"Updated context task status to '{new_status}'."
                else:
                    log_msg = f"No active task context found to update status to '{new_status}'."
                            
            elif label in ["Approval Step", "Approval Needed"]:
                approver_id = config.get('approvers')
                if approver_id:
                    try:
                        user = User.objects.get(id=approver_id)
                        mode = config.get('mode', 'parallel')
                        log_msg = f"Requested {mode} approval from {user.get_full_name() or user.username}."
                        if Notification:
                            Notification.objects.create(
                                type="workflow_approval",
                                title="Approval Required",
                                message=f"Your approval is required to proceed with workflow: '{workflow.name}'",
                                link="/workflow-automation"
                            )
                        if user.email:
                            from django.core.mail import send_mail
                            try:
                                send_mail(
                                    subject=f"Approval Required: {workflow.name}",
                                    message=f"Hello {user.get_full_name() or user.username},\n\nYour approval is required to proceed with workflow '{workflow.name}'.\n\n- System Bot",
                                    from_email='system@company.local',
                                    recipient_list=[user.email],
                                    fail_silently=True,
                                )
                                log_msg += " Real email dispatched."
                            except Exception:
                                pass
                    except User.DoesNotExist:
                        log_msg = f"Approver ID '{approver_id}' not found. Cannot request approval."
                        
            elif label == "Send Email":
                email_address = config.get('email')
                if email_address:
                    from django.core.mail import send_mail
                    try:
                        send_mail(
                            subject=f"Workflow Notification: {workflow.name}",
                            message=f"Hello,\n\nThis is an automated email from the workflow '{workflow.name}'.\n\n- System Bot",
                            from_email='system@company.local',
                            recipient_list=[email_address],
                            fail_silently=False,
                        )
                        log_msg = f"Successfully dispatched real email to {email_address}."
                    except Exception as e:
                        log_msg = f"Failed to send email to {email_address}. Error: {str(e)}"
                else:
                    log_msg = f"No recipient email configured for Send Email node."
                    
            elif label == "Send Notification":
                title = config.get('title', f"Workflow Alert: {workflow.name}")
                message = config.get('message', 'A workflow automation step was triggered.')
                if Notification:
                    Notification.objects.create(
                        type="workflow_alert",
                        title=title,
                        message=message,
                        link="/workflow-automation"
                    )
                    log_msg = f"Broadcast notification dispatched successfully: '{title}'."

            node_traces[curr] = {
                "status": "Success",
                "timestamp": datetime.datetime.now().isoformat(),
                "log": log_msg
            }
            
            for target_id, handle in adj.get(curr, []):
                # Follow edges matching branch logic
                if branch_taken is None or handle == branch_taken or handle is None:
                    execution_queue.append(target_id)

        log_details_dict = {
            "summary": f"Workflow executed sequentially across {nodes_count} connected nodes.\nAll actions completed and tracked.",
            "node_traces": node_traces
        }

        # Create log
        WorkflowLog.objects.create(
            workflow=workflow,
            status="Success",
            details=json.dumps(log_details_dict)
        )

        # Update workflow stats
        workflow.runs += 1
        workflow.last_run = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        workflow.save()

        serializer = self.get_serializer(workflow)
        return Response(serializer.data, status=status.HTTP_200_OK)

class WorkflowDefinitionViewSet(viewsets.ModelViewSet):
    queryset = WorkflowDefinition.objects.all().order_by('-created_at')
    serializer_class = WorkflowDefinitionSerializer

class WorkflowVersionViewSet(viewsets.ModelViewSet):
    queryset = WorkflowVersion.objects.all().order_by('-published_at')
    serializer_class = WorkflowVersionSerializer

class WorkflowExecutionViewSet(viewsets.ModelViewSet):
    queryset = WorkflowExecution.objects.all().order_by('-started_at')
    serializer_class = WorkflowExecutionSerializer

class ApprovalTaskViewSet(viewsets.ModelViewSet):
    queryset = ApprovalTask.objects.all().order_by('-sla_deadline')
    serializer_class = ApprovalTaskSerializer