# Generated by Django 5.2.14 on 2026-06-12 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PM', 'Product Manager'), ('DEV', 'Developer'), ('DESIGN', 'Designer'), ('QA', 'QA Engineer'), ('DEVOPS', 'DevOps Engineer'), ('ANALYST', 'Business Analyst'), ('HR', 'HR Specialist')], default='DEV', max_length=20)),
                ('weekly_capacity', models.FloatField(default=40.0)),
                ('initials', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_employees', to='resources.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='res_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Medium'), ('P4', 'Low')], default='P3', max_length=2)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=20)),
                ('estimated_effort', models.FloatField(default=0.0)),
                ('effort_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=10)),
                ('is_urgent', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='res_tasks', to='resources.employeeprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_created_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
            ],
            options={
                'ordering': ['priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ResourceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('overloaded', 'Overloaded Resource'), ('urgent', 'Multiple Urgent Tasks'), ('deadline', 'Overlapping Deadlines')], max_length=20)),
                ('message', models.TextField()),
                ('resolution', models.CharField(choices=[('open', 'Open'), ('reassigned', 'Reassigned Task'), ('adjusted', 'Deadline Adjusted'), ('override', 'Overridden')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_conflicts', to='resources.employeeprofile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
                ('tasks', models.ManyToManyField(blank=True, related_name='res_conflicts', to='resources.resourcetask')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('leave', 'Annual Leave'), ('sick', 'Sick Leave'), ('holiday', 'Public Holiday'), ('other', 'Other')], default='leave', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_time_offs', to='resources.employeeprofile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CapacityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('monday_hours', models.FloatField(default=8.0)),
                ('tuesday_hours', models.FloatField(default=8.0)),
                ('wednesday_hours', models.FloatField(default=8.0)),
                ('thursday_hours', models.FloatField(default=8.0)),
                ('friday_hours', models.FloatField(default=8.0)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_capacity_plans', to='resources.employeeprofile')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('employee', 'week_start')},
            },
        ),
    ]
