# Generated by Django 5.2.14 on 2026-06-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
    ]
