# Generated by Django 5.2.14 on 2026-07-18 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
