# Generated by Django 5.2.14 on 2026-07-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_policy_organization_alter_policy_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
