# Generated by Django 5.2.14 on 2026-07-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_advanced_settings'),
        ('recognition', '0002_birthday_site_kudos_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_site_records', to='organization.site'),
        ),
    ]
