# Generated by Django 5.2.14 on 2026-06-12 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAccessMapping',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('permissions', models.JSONField(default=dict)),
                ('module_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feature_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('access_scope', models.CharField(default='Self', max_length=50)),
                ('dashboard_type', models.CharField(default='Standard', max_length=50)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('cross_department_access', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
