# Generated by Django 5.2.14 on 2026-07-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_common',
            field=models.BooleanField(default=False, help_text='If true, visible to everyone in the organization'),
        ),
    ]
